@startuml
left to right direction
skinparam PackageStyle rect
skinparam style strictuml
skinparam defaultfontname Verdana
skinparam DefaultTextAlignment center
skinparam Linetype agent


'ACTEURS
:AC01\nUtilisateur: as AC01
:AC02\nAPI de Prometheus: as AC02
:AC03\nBase de données\nmySQL: as AC03


'LE PROJET ODYSSÉE
rectangle "Projet Odyssée" {
  'CAS D'UTILISATION
  (CU01 - Récupérer les données dans les bases de données) as (CU01)
  (CU02 - Afficher un dashboard) as (CU02)
  '(CU0X - Afficher les données dans un graphique) as (CU0X) 'Finalement ne correspond pas à CAR01, mais correspond à CAR02
  '(CU0X - Afficher les données dans un tableau) as (CU0X) 'Finalement ne correspond pas à CAR01, mais correspond à CAR02


  'LIENS ENTRE ACTEURS ET CAS D'UTILISATION
  AC01 --> (CU01)
  AC01 --> (CU02)

  (CU01) -- AC02
  (CU01) -- AC03


  'LIENS ENTRE LES CAS D'UTILISATION
  (CU01) .> (CU02) : extend
}

@enduml